const ArrayofBlogs = [    
    {
        ID : '1',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 1,
        Child: 0,
        Image : "https://www.vivantahotels.com/content/dam/gateway/hotels/E.Mbypass,Kolkata/images/welcome/GatewayKolkata-Facadepan-shot.jpg",
        Price : "₹ 4,139+ ₹ 497 taxes & fees",
        Body : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '2',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 1,
        Child  : 1,
        Image  : "https://r1imghtlak.mmtcdn.com/0c04b563-7514-482d-be00-117008c21cff.jpeg?downsize=*:500&crop=990:500",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '3',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 1,
        Child  : 2,
        Image  : "https://www.itchotels.com/content/dam/itchotels/in/umbrella/itc/hotels/itcroyalbengal-kolkata/images/overview-landing-page/overview/desktop/exterior-dusk-with-pond.png",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '4',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 2,
        Child  : 0,
        Image  : "https://r1imghtlak.mmtcdn.com/0f00d12b-9701-420b-b944-7cf35bc4d064.jpg?&output-quality=75&downsize=520:350&crop=520:350;2,0&output-format=jpg&downsize=480:336&crop=480:336",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '5',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 2,
        Child  : 1,
        Image  : "https://media.easemytrip.com/media/hotel/shl-2108900068179/external/externalxs9crr.jpg",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '6',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 2,
        Child  : 2,
        Image  : "https://www.thelalit.com/wp-content/uploads/2021/07/Kolkata-Facade-M.jpg",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },

]


exports.ArrayofBlogs = ArrayofBlogs;