const ArrayofBlogs = [    

    {
        ID : '2',
        Title  : "The Park Kolkata",
        Author : "The Park Kolkata",
        Adults : 1,
        Child: 0,
        Image1 : "https://r1imghtlak.mmtcdn.com/57663784996211e8bfae0adfcdb46c1c.jpg?&output-quality=75&downsize=910:612&crop=910:612;4,0&output-format=webp",
        Image2 : "https://theasiacollective.com/wp-content/uploads/2020/03/Taj-Lake-Palace-2.jpg",
        Image3 : "https://media.cnn.com/api/v1/images/stellar/prod/171122165337-ultimate-india-hotels-wildflower-hall-shimla-in-the-himalayas-an-oberoi-resort.jpg?q=w_1110,c_fill",
        Image4 : "https://i0.wp.com/theluxurytravelexpert.com/wp-content/uploads/2019/07/UMAID-BHAWAN-PALACE-JODHPUR-INDIA.jpg?ssl=1",
        Image5 : "https://r1imghtlak.mmtcdn.com/daced7747e4411eb9a5e0242ac110002.jpg",
        Price : "₹ 4,139+ ₹ 497 taxes & fees",
        Body : "An extravagant hotel renowned for its nightlife and dining, The Park Kolkata is a great choice for fun-loving guests as well as business travellers.",
        Rating : 4.5,
        Reviews : 1234,
        Location_Surroundings : "The property is located on Park Street, a historic road in the city centre. Also known as Mother Teresa Sarani, this neighbourhood is renowned for its excellent dining scene.Staying here enable guests to easily visit top attractions and other parts of the city.With the market in the vicinity, the property has proved to be a good choice for travellers.",
        Category : "Advertisement",
        SubCategory : "Hotels",
    },

    {
        ID : '1',
        Title  : "The Park Kolkata",
        Author : "The Park Kolkata",
        Adults : 1,
        Child: 0,
        Image1 : "https://r2imghtlak.mmtcdn.com/r2-mmt-htl-image/htl-imgs/200704121625445530-22d98020-7e00-45ee-a1c9-39ec7e084d5f.jpg?&output-quality=75&downsize=520:350&crop=520:350;2,0&output-format=jpg&downsize=480:336&crop=480:336",
        Image2 : "https://r1imghtlak.mmtcdn.com/61e5b06e2e8f11e49f10daf4768ad8d9.jfif",
        Image3 : "https://r1imghtlak.mmtcdn.com/1f27ba1c73a911ec9d5b0a58a9feac02.jpg",
        Image4 : "https://r1imghtlak.mmtcdn.com/ljmisdv1gp6onflmi3jrfln40042.jpg",
        Image5 : "https://r1imghtlak.mmtcdn.com/daced7747e4411eb9a5e0242ac110002.jpg",
        Price : "₹ 4,139+ ₹ 497 taxes & fees",
        Body : "An extravagant hotel renowned for its nightlife and dining, The Park Kolkata is a great choice for fun-loving guests as well as business travellers.",
        Rating : 4.5,
        Reviews : 1234,
        Location_Surroundings : "The property is located on Park Street, a historic road in the city centre. Also known as Mother Teresa Sarani, this neighbourhood is renowned for its excellent dining scene.Staying here enable guests to easily visit top attractions and other parts of the city.With the market in the vicinity, the property has proved to be a good choice for travellers.",
        Category : "Hotels",
    },
    {
        ID : '7',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 1,
        Child: 0,
        Image1 : "https://www.vivantahotels.com/content/dam/gateway/hotels/E.Mbypass,Kolkata/images/welcome/GatewayKolkata-Facadepan-shot.jpg",
        Price : "₹ 4,139+ ₹ 497 taxes & fees",
        Body : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '2',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 1,
        Child  : 1,
        Image1  : "https://r1imghtlak.mmtcdn.com/0c04b563-7514-482d-be00-117008c21cff.jpeg?downsize=*:500&crop=990:500",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '3',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 1,
        Child  : 2,
        Image1  : "https://www.itchotels.com/content/dam/itchotels/in/umbrella/itc/hotels/itcroyalbengal-kolkata/images/overview-landing-page/overview/desktop/exterior-dusk-with-pond.png",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '4',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 2,
        Child  : 0,
        Image1  : "https://r1imghtlak.mmtcdn.com/0f00d12b-9701-420b-b944-7cf35bc4d064.jpg?&output-quality=75&downsize=520:350&crop=520:350;2,0&output-format=jpg&downsize=480:336&crop=480:336",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '5',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 2,
        Child  : 1,
        Image1  : "https://media.easemytrip.com/media/hotel/shl-2108900068179/external/externalxs9crr.jpg",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },
    {
        ID : '6',
        Title  : "Ginger Goa, Candolim",
        Author : "Luxe Queen Room",
        Adults : 2,
        Child  : 2,
        Image1  : "https://www.thelalit.com/wp-content/uploads/2021/07/Kolkata-Facade-M.jpg",
        Price  : "₹ 4,139+ ₹ 497 taxes & fees",
        Body   : "way from the pristine Candolim Beach. The hotel offers well-appointed rooms, contemporary amenities, and a warm, welcoming ambiance, making it ideal for both leisure and business travelers. Guests can enjoy delicious dining options, a well-equipped fitness center, and seamless connectivity. With its strategic location near popular tourist spots, Ginger Hotel Candolim provides easy access to Goa's rich cultural and natural attractions. It’s the perfect blend of comfort, convenience, and affordability for a memorable stay.",
        Category : "Hotels",
    },

]


exports.ArrayofBlogs = ArrayofBlogs;